### ISSUE TITLE
Deploy the App

### ISSUE THREAD

**Issue by stevenvegt** [kevinetore/Caren-fitbit-syncer#4]
Many steps to deploy the app:

* [x] Find hosting party such as Heroku.
* [x] Embed some error logging service like Rollbar
* [x] Safety
  * [x] Invalidate all current secrets
  * [x] Remove all secrets from the codebase
  * [x] Reqeust new secrets and put these these into Environment vars

**Comment by kevinetore** [comment]
I was trying to implement Rollbar into Heroku, sadly Rollbar does not support Elixir on Heroku (yet). For now I've implemented [AppSignal](https://appsignal.com/) into the application, as far as I can see it looks really promising!
